CREATE TABLE [dbo].[OtherDispatchAllocation] (
    [OtherDispatchAllocationID] UNIQUEIDENTIFIER CONSTRAINT [DF_OtherDispatchAllocation_OtherDispatchAllocationID] DEFAULT (newsequentialid()) ROWGUIDCOL NOT NULL,
    [PartitionID]               INT              NOT NULL,
    [AgreementDate]             DATETIME         NOT NULL,
    [CommodityID]               INT              NOT NULL,
    [EstimatedDispatchDate]     DATETIME         NOT NULL,
    [HubID]                     INT              NOT NULL,
    [ToHubID]                   INT              NOT NULL,
    [ProgramID]                 INT              NOT NULL,
    [UnitID]                    INT              NOT NULL,
    [QuantityInUnit]            DECIMAL (18, 3)  NOT NULL,
    [QuantityInMT]              DECIMAL (18, 3)  NOT NULL,
    [ReasonID]                  INT              NOT NULL,
    [ReferenceNumber]           NVARCHAR (50)    NOT NULL,
    [Remark]                    NVARCHAR (4000)  NULL,
    [ShippingInstructionID]     INT              NOT NULL,
    [ProjectCodeID]             INT              NOT NULL,
    [TransporterID]             INT              NULL,
    [IsClosed]                  BIT              CONSTRAINT [DF_OtherDispatchAllocation_IsClosed] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OtherDispatchAllocation_1] PRIMARY KEY CLUSTERED ([OtherDispatchAllocationID] ASC),
    CONSTRAINT [FK_OtherDispatchAllocation_Commodity] FOREIGN KEY ([CommodityID]) REFERENCES [dbo].[Commodity] ([CommodityID]),
    CONSTRAINT [FK_OtherDispatchAllocation_Hub] FOREIGN KEY ([HubID]) REFERENCES [dbo].[Hub] ([HubID]),
    CONSTRAINT [FK_OtherDispatchAllocation_Hub1] FOREIGN KEY ([ToHubID]) REFERENCES [dbo].[Hub] ([HubID]),
    CONSTRAINT [FK_OtherDispatchAllocation_Program] FOREIGN KEY ([ProgramID]) REFERENCES [dbo].[Program] ([ProgramID]),
    CONSTRAINT [FK_OtherDispatchAllocation_ProjectCode] FOREIGN KEY ([ProjectCodeID]) REFERENCES [dbo].[ProjectCode] ([ProjectCodeID]),
    CONSTRAINT [FK_OtherDispatchAllocation_ShippingInstruction] FOREIGN KEY ([ShippingInstructionID]) REFERENCES [dbo].[ShippingInstruction] ([ShippingInstructionID]),
    CONSTRAINT [FK_OtherDispatchAllocation_Transporter] FOREIGN KEY ([TransporterID]) REFERENCES [dbo].[Transporter] ([TransporterID])
);

