CREATE TABLE [Procurement].[Transporter] (
    [TransporterID]       INT             IDENTITY (1, 1) NOT NULL,
    [Name]                NVARCHAR (255)  NOT NULL,
    [Region]              NVARCHAR (255)  NULL,
    [SubCity]             NVARCHAR (255)  NULL,
    [Zone]                NVARCHAR (255)  NULL,
    [Woreda]              NVARCHAR (255)  NULL,
    [Kebele]              NVARCHAR (255)  NULL,
    [HouseNo]             NVARCHAR (255)  NULL,
    [TelephoneNo]         NVARCHAR (255)  NULL,
    [MobileNo]            NVARCHAR (255)  NULL,
    [Email]               NVARCHAR (255)  NULL,
    [Ownership]           NVARCHAR (255)  NULL,
    [VehicleCount]        INT             NULL,
    [LiftCapacityFrom]    DECIMAL (19, 5) NULL,
    [LiftCapacityTo]      DECIMAL (19, 5) NULL,
    [LiftCapacityTotal]   DECIMAL (19, 5) NULL,
    [Capital]             DECIMAL (19, 5) NULL,
    [EmployeeCountMale]   INT             NULL,
    [EmployeeCountFemale] INT             NULL,
    [OwnerName]           NVARCHAR (255)  NULL,
    [OwnerMobile]         NVARCHAR (255)  NULL,
    [ManagerName]         NVARCHAR (255)  NULL,
    [ManagerMobile]       NVARCHAR (255)  NULL,
    [ExperienceFrom]      DATETIME        NULL,
    [ExperienceTo]        DATETIME        NULL,
    CONSTRAINT [PK_Transporter] PRIMARY KEY CLUSTERED ([TransporterID] ASC)
);

