CREATE TABLE [dbo].[Transaction] (
    [TransactionID]         UNIQUEIDENTIFIER CONSTRAINT [DF_Transaction_TransactionID] DEFAULT (newsequentialid()) ROWGUIDCOL NOT NULL,
    [PartitionID]           INT              CONSTRAINT [DF_Transaction_PartitionID] DEFAULT ((0)) NOT NULL,
    [TransactionGroupID]    UNIQUEIDENTIFIER NULL,
    [LedgerID]              INT              NOT NULL,
    [HubOwnerID]            INT              NOT NULL,
    [AccountID]             INT              NOT NULL,
    [HubID]                 INT              NOT NULL,
    [StoreID]               INT              NOT NULL,
    [Stack]                 INT              NULL,
    [ProjectCodeID]         INT              NOT NULL,
    [ShippingInstructionID] INT              NOT NULL,
    [ProgramID]             INT              NOT NULL,
    [ParentCommodityID]     INT              NOT NULL,
    [CommodityID]           INT              NOT NULL,
    [CommodityGradeID]      INT              NULL,
    [QuantityInMT]          DECIMAL (18, 3)  NOT NULL,
    [QuantityInUnit]        DECIMAL (18, 3)  NOT NULL,
    [UnitID]                INT              NOT NULL,
    [TransactionDate]       DATETIME         NOT NULL,
    CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED ([TransactionID] ASC),
    CONSTRAINT [FK_Transaction_Account] FOREIGN KEY ([AccountID]) REFERENCES [dbo].[Account] ([AccountID]),
    CONSTRAINT [FK_Transaction_Commodity] FOREIGN KEY ([ParentCommodityID]) REFERENCES [dbo].[Commodity] ([CommodityID]),
    CONSTRAINT [FK_Transaction_Commodity1] FOREIGN KEY ([CommodityID]) REFERENCES [dbo].[Commodity] ([CommodityID]),
    CONSTRAINT [FK_Transaction_CommodityGrade] FOREIGN KEY ([CommodityGradeID]) REFERENCES [dbo].[CommodityGrade] ([CommodityGradeID]),
    CONSTRAINT [FK_Transaction_HubOwner] FOREIGN KEY ([HubOwnerID]) REFERENCES [dbo].[HubOwner] ([HubOwnerID]),
    CONSTRAINT [FK_Transaction_Ledger] FOREIGN KEY ([LedgerID]) REFERENCES [dbo].[Ledger] ([LedgerID]),
    CONSTRAINT [FK_Transaction_Program] FOREIGN KEY ([ProgramID]) REFERENCES [dbo].[Program] ([ProgramID]),
    CONSTRAINT [FK_Transaction_ProjectCode] FOREIGN KEY ([ProjectCodeID]) REFERENCES [dbo].[ProjectCode] ([ProjectCodeID]),
    CONSTRAINT [FK_Transaction_ShippingInstruction] FOREIGN KEY ([ShippingInstructionID]) REFERENCES [dbo].[ShippingInstruction] ([ShippingInstructionID]),
    CONSTRAINT [FK_Transaction_Store] FOREIGN KEY ([StoreID]) REFERENCES [dbo].[Store] ([StoreID]),
    CONSTRAINT [FK_Transaction_TransactionGroup1] FOREIGN KEY ([TransactionGroupID]) REFERENCES [dbo].[TransactionGroup] ([TransactionGroupID]),
    CONSTRAINT [FK_Transaction_Unit] FOREIGN KEY ([UnitID]) REFERENCES [dbo].[Unit] ([UnitID]),
    CONSTRAINT [FK_Transaction_Warehouse] FOREIGN KEY ([HubID]) REFERENCES [dbo].[Hub] ([HubID])
);

